src/ApiClientCodeGen.VSIX/Generators/NSwagStudio/NSwagStudioCodeGenerator.cs
Try to remove the cached Swagger.json spec contained in the NSwag Studio file
=> Fix issue where NSwag Studio generated output uses the cached Swagger JSON spec

README.md, src/ApiClientCodeGen.VSIX/ApiClientCodeGen.VSIX.csproj, src/ApiClientCodeGen.VSIX/Commands/AddNew/NewRestClientCommand.cs, src/ApiClientCodeGen.VSIX/Generators/FileHelper.cs, src/ApiClientCodeGen.VSIX/Generators/OpenApi/OpenApiCSharpCodeGenerator.cs, src/ApiClientCodeGen.VSIX/packages.config
Changes here use the version 4.0.0 of the OpenAPI Generator tool
This also fixes #25 by setting the Build Action of the OpenAPI specification file to None when adding it via the Add - New REST API Client context menu
=> OpenAPI Generator v4.0.0

src/ApiClientCodeGen.VSIX/Commands/CustomTool/CustomToolSetter.cs, src/ApiClientCodeGen.VSIX/Extensions/ProjectExtensions.cs, src/ApiClientCodeGen.VSIX/NuGet/PackageDependency.cs, src/ApiClientCodeGen.VSIX/NuGet/PackageDependencyListProvider.cs
This resolves issue #31 where the Newtonsoft.Json nuget package was always updated (or downgraded) to version 12.0.1
=> Do not update Newtonsoft.Json NuGet package

src/ApiClientCodeGen.Tests/NuGet/PackageDependencyListProviderTests.cs, src/ApiClientCodeGen.VSIX/ApiClientCodeGen.VSIX.csproj, src/ApiClientCodeGen.VSIX/Extensions/ProjectExtensions.cs, src/ApiClientCodeGen.VSIX/NuGet/PackageDependencies.cs, src/ApiClientCodeGen.VSIX/NuGet/PackageDependencyListProvider.cs
This resolves issue #29 and #41 
Add these NuGet packages when generating code:
- System.Runtime.Serialization.Primitives 
- System.ComponentModel.Annotations
These packages are used by NSwag, Swagger Codegen, and OpenAPI Generator
=> Fix Missing Package References

src/ApiClientCodeGen.Tests/NuGet/PackageDependencyListProviderTests.cs, src/ApiClientCodeGen.VSIX/NuGet/PackageDependencyListProvider.cs
=> [FIX] AutoRest v2.0.4283 generated code fails to build due to missing Newtonsoft.Json reference

src/ApiClientCodeGen.Tests/NuGet/PackageDependencyListProviderTests.cs, src/ApiClientCodeGen.Tests/NuGet/PackageDependencyTests.cs, src/ApiClientCodeGen.VSIX/ApiClientCodeGen.VSIX.csproj, src/ApiClientCodeGen.VSIX/Core/ProjectTypes.cs, src/ApiClientCodeGen.VSIX/Extensions/ProjectExtensions.cs, src/ApiClientCodeGen.VSIX/NuGet/PackageDependencies.cs, src/ApiClientCodeGen.VSIX/NuGet/PackageDependency.cs, src/ApiClientCodeGen.VSIX/NuGet/PackageDependencyListProvider.cs, src/ApiClientCodegen.IntegrationTests/ApiClientCodegen.IntegrationTests.csproj, src/ApiClientCodegen.IntegrationTests/Build/Projects/SwaggerProjectFileContents.cs
This resolves #49
There aren't MIcrosoft provided API's (or at least I couldn't find them) for checking the Project type so I had to introduce a poor man way of checking if a project is a .NET Standard project by simply checking if the "netstandard" text is present in the Project file
=> Microsoft csharp nuget package

.github/workflows/vsmac.yml, build/templates/vsmac.yml, src/ApiClientCodeGen.VSMac/ApiClientCodeGen.VSMac.csproj, src/Makefile
All of the sudden using `msbuild` to build the Visual Studio for Mac on the hosted MacOS agents. 
```
/Applications/Visual\ Studio.app/Contents/MacOS/vstool setup pack ./ApiClientCodeGen.VSMac/bin/Release/net471/ApiClientCodeGen.VSMac.dll -format:mpack -debugSymbols:true
INFO [2020-10-31 12:25:14Z]: Did not find previous version from which to migrate data
Visual Studio Extension Setup Utility
ERROR: Could not read add-in file: ./ApiClientCodeGen.VSMac/bin/Release/net471/ApiClientCodeGen.VSMac.dll
```
Switching to using `vstool build` to build the solution seems to have solved the issue
This resolves #95
=> Fix Visual Studio for Mac Extension builds

src/VSIX/ApiClientCodeGen.VSIX/Commands/AddNew/NewAutoRestClientCommand.cs, src/VSIX/ApiClientCodeGen.VSIX/Commands/AddNew/NewRestClientCommand.cs, src/VSIX/ApiClientCodeGen.VSIX/Extensions/ProjectExtensions.cs
=> Fix Missing AutoRest v3 package references when using "Add New REST API Client" command

src/CLI/ApiClientCodeGen.CLI/Program.cs, src/Core/ApiClientCodeGen.Core.Tests/Command/OpenApiGeneratorFactoryTests.cs, src/Core/ApiClientCodeGen.Core.Tests/Generators/OpenApi/OpenApiCSharpCodeGeneratorExceptionTests.cs, src/Core/ApiClientCodeGen.Core/Commands/OpenApiGeneratorCommand.cs, src/Core/ApiClientCodeGen.Core/Commands/OpenApiGeneratorFactory.cs, src/Core/ApiClientCodeGen.Core/Generators/OpenApi/OpenApiCSharpCodeGenerator.cs, src/Core/ApiClientCodeGen.Core/Options/OpenApiGenerator/DefaultOpenApiGeneratorOptions.cs, src/Core/ApiClientCodeGen.Core/Options/OpenApiGenerator/IOpenApiGeneratorOptions.cs, src/Core/ApiClientCodeGen.Tests.Common/Fixtures/OpenApi3/OpenApiCodeGeneratorFixture.cs, src/Core/ApiClientCodeGen.Tests.Common/Fixtures/OpenApi3/Yaml/OpenApiCodeGeneratorFixture.cs, src/Core/ApiClientCodeGen.Tests.Common/Fixtures/OpenApiCodeGeneratorFixture.cs, src/Core/ApiClientCodeGen.Tests.Common/Fixtures/Yaml/OpenApiCodeGeneratorFixture.cs, src/VSIX/ApiClientCodeGen.Tests/Generators/CodeGeneratorFactoryTests.cs, src/VSIX/ApiClientCodeGen.Tests/Generators/OpenApi/OpenApiCSharpCodeGeneratorExceptionTests.cs, src/VSIX/ApiClientCodeGen.Tests/Generators/OpenApi/OpenApiCSharpCodeGeneratorYamlTests.cs, src/VSIX/ApiClientCodeGen.VSIX/ApiClientCodeGen.VSIX.csproj, src/VSIX/ApiClientCodeGen.VSIX/Generators/CodeGeneratorFactory.cs, src/VSIX/ApiClientCodeGen.VSIX/Options/OpenApiGenerator/OpenApiGeneratorOptions.cs, src/VSIX/ApiClientCodeGen.VSIX/Options/OpenApiGenerator/OpenApiGeneratorOptionsPage.cs, src/VSIX/ApiClientCodeGen.VSIX/VSPackage.cs, src/VSIX/ApiClientCodegen.IntegrationTests/CustomTool/CSharpSingleFileCodeGeneratorOpenApi3Tests.cs, src/VSIX/ApiClientCodegen.IntegrationTests/CustomTool/CSharpSingleFileCodeGeneratorOpenApi3YamlTests.cs, src/VSIX/ApiClientCodegen.IntegrationTests/CustomTool/CSharpSingleFileCodeGeneratorTests.cs, src/VSIX/ApiClientCodegen.IntegrationTests/CustomTool/CSharpSingleFileCodeGeneratorYamlTests.cs, src/VSMac/ApiClientCodeGen.VSMac/Container.cs, src/VSMac/ApiClientCodeGen.VSMac/CustomTools/OpenApi/OpenApiGeneratorFactory.cs, src/VSMac/ApiClientCodeGen.VSMac/CustomTools/OpenApi/OpenApiSingleFileCustomTool.cs, src/VSMac/ApiClientCodeGen.VSMac/Makefile
This pull request implements a Visual Studio options page that allows users to change how OpenAPI Generator generates code. This currently only supports the `EmitDefaultValue` option. 
This change adds `--additional-properties optionalEmitDefaultValues=true|false` to the arguments passed to the OpenAPI Generator CLI tool
Resolves issue #246
=> Create options page for OpenAPI Generator settings

.github/workflows/production-tests.yml, .github/workflows/regression-tests.yml, .github/workflows/smoke-tests.yml, README.md, docs/CLI.md, src/CLI/ApiClientCodeGen.CLI/Commands/CSharpCommand.cs, src/CLI/ApiClientCodeGen.CLI/Commands/JMeterCommand.cs, test/utilities.ps1
The changes here updates the structure of the CLI tool commands so that the code generates are grouped by language. 
The root command will now output the following:
```
Usage: rapicgen [command] [options]
Options:
-v|--verbose  Show verbose output
-?|-h|--help  Show help information.
Commands:
csharp        Generate C# API client
jmeter        Generate Apache JMeter test plans
typescript    Generate TypeScript API client
Run 'rapicgen [command] -?|-h|--help' for more information about a command.
```
**Usage Examples:**
Let's say we have a OpenAPI Specifications document called **Swagger.json**
For starters, we can use the Swagger Petstore spec. Here's an example powershell script for downloading it
```
Invoke-WebRequest -Uri https://petstore.swagger.io/v2/swagger.json -OutFile …
```
=> Restructure CLI Tool commands

src/CLI/ApiClientCodeGen.CLI.Tests/Command/OpenApiCSharpGeneratorCommandTests.cs, src/CLI/ApiClientCodeGen.CLI.Tests/Command/OpenApiCSharpGeneratorFactoryTests.cs, src/CLI/ApiClientCodeGen.CLI.Tests/Command/OpenApiGeneratorCommandTests.cs, src/CLI/ApiClientCodeGen.CLI.Tests/Command/OpenApiGeneratorFactoryTests.cs, src/CLI/ApiClientCodeGen.CLI/Commands/CSharpCommand.cs, src/CLI/ApiClientCodeGen.CLI/Commands/OpenApiCSharpGeneratorCommand.cs, src/CLI/ApiClientCodeGen.CLI/Commands/OpenApiCSharpGeneratorFactory.cs, src/CLI/ApiClientCodeGen.CLI/Commands/OpenApiGeneratorCommand.cs, src/CLI/ApiClientCodeGen.CLI/Commands/OpenApiGeneratorFactory.cs, src/CLI/ApiClientCodeGen.CLI/Commands/RootCommand.cs, src/CLI/ApiClientCodeGen.CLI/Extensions/CodeGeneratorNameExtensions.cs, src/CLI/ApiClientCodeGen.CLI/Program.cs, src/Core/ApiClientCodeGen.Core/Generators/OpenApi/OpenApiCodeGenerator.cs, src/Core/ApiClientCodeGen.Core/Generators/OpenApi/OpenApiJMeterCodeGenerator.cs, src/Core/ApiClientCodeGen.Core/Generators/OpenApi/OpenApiTypeScriptCodeGenerator.cs
The changes here add the `openapi-generator` command to rapicgen for generating code any supported generator by OpenAPI Generator behind the scenes.
```
Usage: rapicgen [command] [options]
Options:
-v|--verbose       Show verbose output
-?|-h|--help       Show help information.
Commands:
csharp             Generate C# API client
jmeter             Generate Apache JMeter test plans
openapi-generator  Generate code using OpenAPI Generator.
See supported generators at https://openapi-generator.tech/docs/generators/
typescript         Generate TypeScript API client
Run 'rapicgen [command] -?|-h|--help' for more information about a command.
```
=> Add CLI Tool support for OpenAPI Generator pass through commands

src/CLI/ApiClientCodeGen.CLI/SentryRemoteLogger.cs, src/Core/ApiClientCodeGen.Core/Generators/AutoRest/AutoRestCSharpCodeGenerator.cs, src/Core/ApiClientCodeGen.Core/Generators/NSwag/NSwagCSharpCodeGenerator.cs, src/Core/ApiClientCodeGen.Core/Generators/NSwagStudio/NSwagStudioCodeGenerator.cs, src/Core/ApiClientCodeGen.Core/Generators/OpenApi/OpenApiCSharpCodeGenerator.cs, src/Core/ApiClientCodeGen.Core/Generators/Swagger/SwaggerCSharpCodeGenerator.cs, src/Core/ApiClientCodeGen.Core/Installer/NpmInstaller.cs, src/Core/ApiClientCodeGen.Core/Installer/WebDownloader.cs, src/Core/ApiClientCodeGen.Core/Logging/AppInsightsRemoteLogger.cs, src/Core/ApiClientCodeGen.Core/Logging/ExceptionlessRemoteLogger.cs, src/Core/ApiClientCodeGen.Core/Logging/IRemoteLogger.cs, src/Core/ApiClientCodeGen.Core/Logging/RemoteLogger.cs, src/Core/ApiClientCodeGen.Core/NpmHelper.cs, src/VSIX/ApiClientCodeGen.VSIX.Shared/SentryRemoteLogger.cs
The changes here logs dependency failures to application insights using the support key as the anonymous user
=> Track Dependency Failures in Application Insights

src/CLI/ApiClientCodeGen.CLI/SentryRemoteLogger.cs, src/Core/ApiClientCodeGen.Core/Generators/AutoRest/AutoRestCSharpCodeGenerator.cs, src/Core/ApiClientCodeGen.Core/Generators/NSwag/NSwagCSharpCodeGenerator.cs, src/Core/ApiClientCodeGen.Core/Generators/NSwagStudio/NSwagStudioCodeGenerator.cs, src/Core/ApiClientCodeGen.Core/Generators/OpenApi/OpenApiCSharpCodeGenerator.cs, src/Core/ApiClientCodeGen.Core/Generators/ProcessLauncher.cs, src/Core/ApiClientCodeGen.Core/Generators/Swagger/SwaggerCSharpCodeGenerator.cs, src/Core/ApiClientCodeGen.Core/Installer/NpmInstaller.cs, src/Core/ApiClientCodeGen.Core/Installer/WebDownloader.cs, src/Core/ApiClientCodeGen.Core/Logging/AppInsightsRemoteLogger.cs, src/Core/ApiClientCodeGen.Core/Logging/DependencyContext.cs, src/Core/ApiClientCodeGen.Core/Logging/ExceptionlessRemoteLogger.cs, src/Core/ApiClientCodeGen.Core/Logging/IRemoteLogger.cs, src/Core/ApiClientCodeGen.Core/Logging/RemoteLogger.cs, src/Core/ApiClientCodeGen.Core/NpmHelper.cs, src/VSIX/ApiClientCodeGen.VSIX.Shared/SentryRemoteLogger.cs, src/VSMac/ApiClientCodeGen.VSMac/SentryRemoteLogger.cs
The changes here track the dependency execution time and failures for the following dependencies:
- NPM
- Java
- NSwag
- NSwagStudio
- OpenAPI Generator
- AutoRest
- Swagger Codegen CLI
- HTTP downloads
=> Track dependency failures and execution performance anonymously

.github/workflows/cli-tool.yml, .github/workflows/release.yml, .github/workflows/vsix.yml, README.md, docs/Marketplace.md, src/VSIX/ApiClientCodeGen.VSIX/source.extension.vsixmanifest
I decided to remove support for Visual Studio 2017 as this product is now 5 years old and is preventing moving forward to newer dependencies. Visual Studio 2017 has an internal hard dependency on Newtonsoft.Json v9.0 but NSwag has now bumped their minimal Newtonsoft.Json version to v10.0.1. 
It's time to move on...
=> Remove Visual Studio 2017 support

src/VSIX/ApiClientCodeGen.VSIX.Shared/VsPackage.cs, src/VSIX/ApiClientCodeGen.VSIX.Shared/Windows/OutputWindow.cs
=> Fix Visual Studio 2022 crash when used in MAUI projects

.github/workflows/cli-tool.yml, .github/workflows/release.yml, .github/workflows/sonar-cloud.yml, .github/workflows/unit-tests.yml, src/CLI/ApiClientCodeGen.CLI.Tests/ApiClientCodeGen.CLI.Tests.csproj, src/CLI/ApiClientCodeGen.CLI/ApiClientCodeGen.CLI.csproj, src/Core/ApiClientCodeGen.Core.IntegrationTests/ApiClientCodeGen.Core.IntegrationTests.csproj, src/Core/ApiClientCodeGen.Core.Tests/ApiClientCodeGen.Core.Tests.csproj, src/Core/ApiClientCodeGen.Core/ApiClientCodeGen.Core.csproj, src/Makefile
This upgrades the CLI Tool, Rapicgen to target .NET 6.0
=> Upgrade Rapicgen CLI Tool to target .NET 6.0

README.md, docs/Marketplace.md, docs/Marketplace2022.md, docs/VisualStudioForMac.md, src/Core/ApiClientCodeGen.Core/Resource.Designer.cs, src/Core/ApiClientCodeGen.Core/Resource.resx
The changes upgrades [OpenAPI Generator](https://github.com/OpenAPITools/openapi-generator) to [v6.3.0](https://github.com/OpenAPITools/openapi-generator/releases/tag/v6.3.0)
=> OpenAPI Generator v6.3.0

src/Core/ApiClientCodeGen.Core.Tests/NuGet/PackageDependencyListProviderTests.cs, src/Core/ApiClientCodeGen.Core/NuGet/PackageDependencies.cs, src/Core/ApiClientCodeGen.Core/NuGet/PackageDependencyListProvider.cs, src/Core/ApiClientCodeGen.Core/SupportedCodeGenerator.cs, src/VSIX/ApiClientCodeGen.VSIX.Dev17/VSCommandTable.vsct, src/VSIX/ApiClientCodeGen.VSIX.Shared/ApiClientCodeGen.VSIX.Shared.projitems, src/VSIX/ApiClientCodeGen.VSIX.Shared/Commands/AddNew/NewKiotaClientCommand.cs, src/VSIX/ApiClientCodeGen.VSIX.Shared/Commands/CustomTool/KiotaCodeGeneratorCustomToolSetter.cs, src/VSIX/ApiClientCodeGen.VSIX.Shared/CustomTool/Kiota/KiotaCSharpCodeGenerator.cs, src/VSIX/ApiClientCodeGen.VSIX.Shared/CustomTool/Kiota/KiotaCodeGenerator.cs, src/VSIX/ApiClientCodeGen.VSIX.Shared/Extensions/SupportedCodeGeneratorExtensions.cs, src/VSIX/ApiClientCodeGen.VSIX.Shared/Generators/CodeGeneratorFactory.cs, src/VSIX/ApiClientCodeGen.VSIX.Shared/VsPackage.cs, src/VSIX/ApiClientCodeGen.VSIX/VSCommandTable.vsct, src/VSIX/ApiClientCodegen.IntegrationTests/CustomTool/CSharpSingleFileCodeGeneratorTests.cs
The changes in this pull request introduces support for generating API clients using [Microsoft Project Kiota](https://github.com/microsoft/kiota)
The Visual Studio extension will automatically install the required NuGet packages to build Kiota generated code
=> Add support for Kiota in Visual Studio Extensions

src/CLI/ApiClientCodeGen.CLI/Commands/CSharp/OpenApiCSharpGeneratorCommand.cs, src/Core/ApiClientCodeGen.Core/Generators/OpenApi/OpenApiCSharpCodeGenerator.cs, src/Core/ApiClientCodeGen.Core/Options/OpenApiGenerator/DefaultOpenApiGeneratorOptions.cs, src/Core/ApiClientCodeGen.Core/Options/OpenApiGenerator/IOpenApiGeneratorOptions.cs, src/Core/ApiClientCodeGen.Tests.Common/ApiClientCodeGen.Tests.Common.csproj, src/Core/ApiClientCodeGen.Tests.Common/Build/Projects/OpenApiGeneratorProjectFileContents.cs, src/Core/ApiClientCodeGen.Tests.Common/Resources/Swagger.config.json, src/Core/ApiClientCodeGen.Tests.Common/Resources/Swagger.config.yaml, src/Core/ApiClientCodeGen.Tests.Common/TestWithResources.cs, src/VSIX/ApiClientCodeGen.VSIX.Shared/Options/OpenApiGenerator/OpenApiGeneratorOptions.cs, src/VSIX/ApiClientCodeGen.VSIX.Shared/Options/OpenApiGenerator/OpenApiGeneratorOptionsPage.cs
This implements #610 
The changes here allow users to include a `.config.json` or `.config.yaml` file to use an OpenAPI Generator configuration file. The configuration file must be placed right beside the OpenAPI specificaitons document and with the extension `.config.json` or `.config.yaml` depending on the format of the specifications file
It looks something like this:
Works with YAML too
It's also possible to use a YAML spec with a JSON config file
And a JSON spec with a YAML config file
=> Add support for OpenAPI Generator configuration files

src/VSIX/ApiClientCodeGen.VSIX.Shared/Windows/EnterOpenApiSpecDialog.Designer.cs, src/VSIX/ApiClientCodeGen.VSIX.Shared/Windows/EnterOpenApiSpecDialog.cs
Refactored the method of displaying status messages in `EnterOpenApiSpecDialog` to use a new private method, `ShowStatusMessage()`. This change was made to increase code reuse, improve readability and reduce the susceptibility to errors. This also makes it easier to manage and possibly change the behavior of status message display in future.
Buttons and status labels within the `EnterOpenApiSpecDialog`were slightly off in their vertical positioning. This commit adjusts the Y-coordinate for the `OK`, `Cancel`, `AddCustomHeaders` buttons and `Status` , `MarketplaceLink` labels  to ensure proper alignment and improve the visual appearance of the dialog. In addition, the overall ClientSize of the dialog has been increased to accommodate these changes without overlap.
=> Ensure that the marketplace review link does not block status messages

.github/workflows/release.yml, .github/workflows/vsix.yml, .vscode/settings.json
This pull request updates the VSIX build workflows to disable extension deployment. It includes the following commits:
- Add default solution path to .vscode settings
- Update VSIX build workflows to disable extension deployment
=> Update VSIX build workflows to disable extension deployment

src/VSIX/ApiClientCodeGen.VSIX.Dev17/VSCommandTable.vsct, src/VSIX/ApiClientCodeGen.VSIX/VSCommandTable.vsct
=> Fix typo "Rifitter" in Visual Studio context menus

src/Core/ApiClientCodeGen.Core/Generators/Kiota/KiotaCodeGenerator.cs
The changes here fix the issue where Kiota generates multiple files when run using the custom tool if the `kiota-lock.json` file is present
This fixes #905
=> Ensure Kiota custom tool respects the Generate Multiple Files option

src/VSIX/ApiClientCodeGen.VSIX.Dev17/ApiClientCodeGen.VSIX.Dev17.csproj, src/VSIX/ApiClientCodeGen.VSIX/ApiClientCodeGen.VSIX.csproj
Reverts christianhelle/apiclientcodegen#914 because this change breaks the Azure Application Insights library
=> Revert "Update dependency Microsoft.VSSDK.BuildTools to v17.10.2179"

src/VSIX/ApiClientCodeGen.VSIX.Dev17/ApiClientCodeGen.VSIX.Dev17.csproj, src/VSIX/ApiClientCodeGen.VSIX/ApiClientCodeGen.VSIX.csproj
Reverts christianhelle/apiclientcodegen#935 which broke the VSIX package causing Application Insights libraries to fail
=> Revert "Update dependency Microsoft.VSSDK.BuildTools to v17.10.2185"

src/Core/ApiClientCodeGen.Core.Tests/Extensions/EnumGetDescriptionTests.cs, src/Core/ApiClientCodeGen.Core/Options/OpenApiGenerator/OpenApiSupportedTargetFramework.cs
This pull request adds support for .NET 7.0 and .NET 8.0 to the OpenAPI Generator target framework options. 
This allows developers to generate code using these newer versions of .NET and also keep the options aligned with the target frameworks that OpenAPI Generator supports in their [official documentation](https://openapi-generator.tech/docs/generators/csharp/)
This resolves #960
=> Add support for .NET 8.0 to the OpenAPI Generator target framework options

src/Core/ApiClientCodeGen.Core/Generators/OpenApi/OpenApiCSharpCodeGenerator.cs
Adding an extra space at the end of the -c [file] line to match the other lines.
=> Using config file and addl parameters causes a command error

src/Core/ApiClientCodeGen.Core/NuGet/PackageDependencies.cs, src/Core/ApiClientCodeGen.Tests.Common/Build/Projects/KiotaProjectFileContents.cs
This pull request updates the Kiota package dependencies to version 1.12.4. The `Microsoft.Kiota.Abstractions`, `Microsoft.Kiota.Authentication.Azure`, `Microsoft.Kiota.Http.HttpClientLibrary`, `Microsoft.Kiota.Serialization.Form`, `Microsoft.Kiota.Serialization.Json`, `Microsoft.Kiota.Serialization.Text`, and `Microsoft.Kiota.Serialization.Multipart` packages are all updated to version 1.12.4.
=> Update Kiota package dependencies for v1.18.0  compatibility

src/Core/ApiClientCodeGen.Core/NuGet/PackageDependencies.cs, src/Core/ApiClientCodeGen.Tests.Common/Build/Projects/KiotaProjectFileContents.cs, test/GeneratedCode/Kiota/Directory.build.props
This pull request updates the Kiota dependencies to version 1.13.0. The update includes changes in the unit tests and smoke tests as well.
=> Update Kiota dependencies to v1.13.0

src/Core/ApiClientCodeGen.Tests.Common/Build/Projects/NSwagProjectFileContents.cs
the undocumented names (without period in dotnet 5+) can drop their support when move to double-digit (to avoid potential conflicts) [learn.microsoft.com/en-us/dotnet/standard/frameworks#supported-target-frameworks](https://learn.microsoft.com/en-us/dotnet/standard/frameworks#supported-target-frameworks)
=> use correct framework

src/CLI/ApiClientCodeGen.CLI/Commands/CSharp/KiotaCommand.cs, src/Core/ApiClientCodeGen.Core/Generators/Kiota/KiotaCodeGenerator.cs, src/Core/ApiClientCodeGen.Core/Generators/Kiota/KiotaConfiguration.cs, src/Core/ApiClientCodeGen.Core/Generators/Kiota/TypeAccessModifier.cs, src/Core/ApiClientCodeGen.Core/Options/Kiota/DefaultKiotaOptions.cs, src/Core/ApiClientCodeGen.Core/Options/Kiota/IKiotaOptions.cs, src/VSIX/ApiClientCodeGen.VSIX.Shared/Options/Kiota/KiotaOptions.cs, src/VSIX/ApiClientCodeGen.VSIX.Shared/Options/Kiota/KiotaOptionsPage.cs
This pull request introduces a new feature to set the access modifier for generated types in the Kiota code generator. The changes span multiple files to incorporate this new option, including modifications to configuration classes, options interfaces, and the command-line interface.
* **Command Line Interface**:
* [`src/CLI/ApiClientCodeGen.CLI/Commands/CSharp/KiotaCommand.cs`](diffhunk://#diff-efaa25b6f99e148545de4b8ce508e9adc655a9f045ee3d2be809eb6e77b5cc5aR41-R46): Added a new option `type-access-modifier` to set the access modifier for generated types. (`[src/CLI/ApiClientCodeGen.CLI/Commands/CSharp/KiotaCommand.csR41-R46](diffhunk://#diff-efaa25b6f99e148545de4b8ce508e9adc655a9f045ee3d2be809eb6e77b5cc5aR41-R46)`)
* **Core Generator Logic**:
* …
=> Add support --type-access-modifier option for Microsoft Kiota

src/Core/ApiClientCodeGen.Core/NuGet/PackageDependencies.cs, src/Core/ApiClientCodeGen.Tests.Common/Build/Projects/KiotaProjectFileContents.cs, test/GeneratedCode/Kiota/Directory.build.props
This pull request updates the version of various `Microsoft.Kiota` packages across multiple files to ensure consistency and compatibility with the latest features and fixes.
Package version updates:
* [`src/Core/ApiClientCodeGen.Core/NuGet/PackageDependencies.cs`](diffhunk://#diff-95b74b588bc36889e73c960f7d53f320a5d4429cb817f5459fe4cae0d0f08b3cL79-R109): Updated `Microsoft.Kiota` package dependencies from version `1.13.1` to `1.14.0`.
* [`src/Core/ApiClientCodeGen.Tests.Common/Build/Projects/KiotaProjectFileContents.cs`](diffhunk://#diff-4803d3275bddea639ee0b07c0b2d62a4dfc82aed8f67ead1bdb0b2df0d0e4d50L12-R17): Updated `Microsoft.Kiota` package references for `.NET 8.0` and `netstandard2.1` projects from version `1.13.1` to `1.14.0`. …
=> Update Kiota dependencies to v1.14.0

src/Core/ApiClientCodeGen.Core/NuGet/PackageDependencies.cs, src/Core/ApiClientCodeGen.Tests.Common/Build/Projects/KiotaProjectFileContents.cs, test/GeneratedCode/Kiota/Directory.build.props
This pull request updates the version of several `Microsoft.Kiota` package dependencies across multiple files to ensure consistency and take advantage of the latest features and bug fixes. The key changes involve updating the version numbers from `1.14.0` to `1.15.2`.
Updates to package dependencies:
* [`src/Core/ApiClientCodeGen.Core/NuGet/PackageDependencies.cs`](diffhunk://#diff-95b74b588bc36889e73c960f7d53f320a5d4429cb817f5459fe4cae0d0f08b3cL79-R109): Updated version numbers for `Microsoft.Kiota.Abstractions`, `Microsoft.Kiota.Authentication.Azure`, `Microsoft.Kiota.Http.HttpClientLibrary`, `Microsoft.Kiota.Serialization.Form`, `Microsoft.Kiota.Serialization.Json`, `Microsoft.Kiota.Serialization.Text`, and `Microsoft.Kiota.Serialization.Multipart` from `1.14.0` to `1.15.2`.
* …
=> Update Microsoft Kiota dependencies to v1.15.2

.github/workflows/production-tests.yml, .github/workflows/regression-tests.yml, .github/workflows/release.yml, .github/workflows/smoke-tests.yml, .github/workflows/unit-tests.yml, .github/workflows/vsmac.yml
This pull request updates the macOS runner to use `macos-latest` instead of specific macOS versions (`macos-12`). This ensures that the latest macOS version is used for the build and testing processes.
=> Update MacOS runner

src/Core/ApiClientCodeGen.Core/NuGet/PackageDependencies.cs, src/Core/ApiClientCodeGen.Tests.Common/Build/Projects/KiotaProjectFileContents.cs, test/GeneratedCode/Kiota/Directory.build.props
This pull request updates the version of several Microsoft Kiota packages across multiple files. The changes ensure that the codebase uses the latest version of these dependencies.
Package version updates:
* [`src/Core/ApiClientCodeGen.Core/NuGet/PackageDependencies.cs`](diffhunk://#diff-95b74b588bc36889e73c960f7d53f320a5d4429cb817f5459fe4cae0d0f08b3cL79-R109): Updated the package versions for `Microsoft.Kiota.Abstractions`, `Microsoft.Kiota.Authentication.Azure`, `Microsoft.Kiota.Http.HttpClientLibrary`, `Microsoft.Kiota.Serialization.Form`, `Microsoft.Kiota.Serialization.Json`, `Microsoft.Kiota.Serialization.Text`, and `Microsoft.Kiota.Serialization.Multipart` from `1.15.2` to `1.16.0`.
* [`src/Core/ApiClientCodeGen.Tests.Common/Build/Projects/KiotaProjectFileContents.cs`](diffhunk://#di …
=> Update Microsoft Kiota dependencies to v1.16.0

src/Core/ApiClientCodeGen.Core/NuGet/PackageDependencies.cs, src/Core/ApiClientCodeGen.Tests.Common/Build/Projects/KiotaProjectFileContents.cs, test/GeneratedCode/Kiota/Directory.build.props
This pull request includes updates to the version of several `Microsoft.Kiota` package dependencies across multiple files. The most important changes include updating the package versions in `PackageDependencies.cs`, `KiotaProjectFileContents.cs`, and `Directory.build.props`.
Version updates to `Microsoft.Kiota` packages:
* [`src/Core/ApiClientCodeGen.Core/NuGet/PackageDependencies.cs`](diffhunk://#diff-95b74b588bc36889e73c960f7d53f320a5d4429cb817f5459fe4cae0d0f08b3cL79-R109): Updated the version of `Microsoft.Kiota` packages from `1.16.0` to `1.16.1`.
* [`src/Core/ApiClientCodeGen.Tests.Common/Build/Projects/KiotaProjectFileContents.cs`](diffhunk://#diff-4803d3275bddea639ee0b07c0b2d62a4dfc82aed8f67ead1bdb0b2df0d0e4d50L12-R17): Updated the version of `Microsoft.Kiota` packages from …
=> Update Kiota dependencies to v1.16.1

src/Core/ApiClientCodeGen.Core/NuGet/PackageDependencies.cs, src/Core/ApiClientCodeGen.Tests.Common/Build/Projects/KiotaProjectFileContents.cs, test/GeneratedCode/Kiota/Directory.build.props
This pull request includes updates to several package dependencies across multiple files to ensure compatibility with the latest versions. The primary changes involve updating the version of `Microsoft.Kiota` packages from `1.16.3` to `1.16.4`.
Dependency updates:
* [`src/Core/ApiClientCodeGen.Core/NuGet/PackageDependencies.cs`](diffhunk://#diff-95b74b588bc36889e73c960f7d53f320a5d4429cb817f5459fe4cae0d0f08b3cL79-R109): Updated the version of multiple `Microsoft.Kiota` packages from `1.16.3` to `1.16.4`.
* [`src/Core/ApiClientCodeGen.Tests.Common/Build/Projects/KiotaProjectFileContents.cs`](diffhunk://#diff-4803d3275bddea639ee0b07c0b2d62a4dfc82aed8f67ead1bdb0b2df0d0e4d50L12-R17): Updated the version of multiple `Microsoft.Kiota` packages in the `KiotaProjectFileContents` class from …
=> Update Kiota dependencies to v1.16.4

src/VSIX/ApiClientCodeGen.VSIX.Shared/Windows/AddCustomHeaderDialog.cs
This pull request includes changes to the `AddCustomHeaderDialog` class in the `ApiClientCodeGen.VSIX.Shared` project. The main changes involve modifying the `CustomHeader` type to use a class instead of a record and updating how `CustomHeader` instances are created and used.
Changes to `AddCustomHeaderDialog` class:
* Modified the `CustomHeader` type from a record to a class, allowing the properties `Key` and `Value` to be settable.
* Updated the instantiation of `CustomHeader` objects to use object initializer syntax for setting `Key` and `Value` properties
=> Fix non-editable HTTP headers Grid

src/Core/ApiClientCodeGen.Core/External/JavaPathProvider.cs
This pull request includes an important change to the `GetJavaExePath` method in the `JavaPathProvider` class. The change improves the method's ability to locate the Java executable by adding an additional check for an included Java path before throwing an exception.
* [`src/Core/ApiClientCodeGen.Core/External/JavaPathProvider.cs`](diffhunk://#diff-755514a404d98183276e58504f7331bfd4e0027c2318192bfe6b5ac6f5ca353bR43-R46): Modified the `GetJavaExePath` method to check for an included Java path using `PathProvider.GetIncludedJavaPath()` before throwing a `MissingJavaRuntimeException` if the Java executable is not found.
=> Fallback to using included OpenJDK if JAVA_HOME doesn't exist

src/Core/ApiClientCodeGen.Core/NuGet/PackageDependencies.cs, src/Core/ApiClientCodeGen.Tests.Common/Build/Projects/KiotaProjectFileContents.cs, test/GeneratedCode/Kiota/Directory.build.props
This pull request includes updates to the version of various `Microsoft.Kiota` package dependencies across multiple files to ensure consistency and compatibility. The updates are minor version increments.
Version updates:
* [`src/Core/ApiClientCodeGen.Core/NuGet/PackageDependencies.cs`](diffhunk://#diff-95b74b588bc36889e73c960f7d53f320a5d4429cb817f5459fe4cae0d0f08b3cL79-R109): Updated the version of multiple `Microsoft.Kiota` package dependencies from `1.17.1` to `1.17.2`.
* [`src/Core/ApiClientCodeGen.Tests.Common/Build/Projects/KiotaProjectFileContents.cs`](diffhunk://#diff-4803d3275bddea639ee0b07c0b2d62a4dfc82aed8f67ead1bdb0b2df0d0e4d50L12-R17): Updated the version of multiple `Microsoft.Kiota` package dependencies in two sections from `1.17.1` to `1.17.2`. …
=> Update Kiota dependencies to v1.17.2

.github/workflows/cli-tool.yml, .github/workflows/release.yml
This pull request includes updates to the GitHub Actions workflow files to ensure they are using the latest Windows runner. The most important changes include modifying the `runs-on` parameter in multiple workflow files.
Updates to workflow files:
* [`.github/workflows/cli-tool.yml`](diffhunk://#diff-4c3e3afa51772a5df1fbc861efdd9e0885d366fa4f3c1fe35d00bbbf5fe72eb5L27-R27): Changed the `runs-on` parameter from `windows-2022` to `windows-latest`.
* [`.github/workflows/release.yml`](diffhunk://#diff-87db21a973eed4fef5f32b267aa60fcee5cbdf03c67fafdc2a9b553bb0b15f34L16-R16): Updated the `runs-on` parameter to `windows-latest` for both the `CLI` and `VSIX` jobs. [[1]](diffhunk://#diff-87db21a973eed4fef5f32b267aa60fcee5cbdf03c67fafdc2a9b553bb0b15f34L16-R16) …
=> Update workflows to run on windows-latest

README.md, docs/CLI.md, docs/Marketplace.md, docs/Marketplace2022.md, docs/VisualStudioForMac.md, src/CLI/ApiClientCodeGen.CLI/Commands/CSharp/OpenApiCSharpGeneratorCommand.cs, src/CLI/ApiClientCodeGen.CLI/Commands/OpenApiGeneratorCommand.cs, src/Core/ApiClientCodeGen.Core/Generators/OpenApi/OpenApiCSharpCodeGenerator.cs, src/Core/ApiClientCodeGen.Core/Installer/OpenApiGeneratorVersions.cs, src/Core/ApiClientCodeGen.Core/Options/OpenApiGenerator/OpenApiSupportedVersion.cs, src/Core/ApiClientCodeGen.Core/Resource.Designer.cs, src/Core/ApiClientCodeGen.Core/Resource.resx, src/VSIX/ApiClientCodeGen.VSIX.Dev17/VSCommandTable.vsct, src/VSIX/ApiClientCodeGen.VSIX/VSCommandTable.vsct, src/VSMac/ApiClientCodeGen.VSMac/Properties/Manifest.addin.xml, test/utilities.ps1
This pull request updates the OpenAPI Generator version from `v7.12.0` to `v7.13.0` across various parts of the project, including documentation, CLI commands, and resource files. The changes ensure consistency in version references and update download URLs and hash values for the new version.
* Updated OpenAPI Generator version references from `v7.12.0` to `v7.13.0` in `README.md`, `docs/CLI.md`, `docs/Marketplace.md`, `docs/Marketplace2022.md`, and `docs/VisualStudioForMac.md`. [[1]](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L57-R61) [[2]](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L270-R270) [[3]](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L309-R309) …
=> OpenAPI Generator v7.13.0

src/Core/ApiClientCodeGen.Core/NuGet/PackageDependencies.cs, src/Core/ApiClientCodeGen.Tests.Common/Build/Projects/KiotaProjectFileContents.cs, test/GeneratedCode/Kiota/Directory.build.props
This pull request updates the version of multiple `Microsoft.Kiota` package dependencies from `1.17.3` to `1.19.0` across several files in the project. These changes ensure compatibility with the latest features and fixes provided by the updated packages.
* [`src/Core/ApiClientCodeGen.Core/NuGet/PackageDependencies.cs`](diffhunk://#diff-95b74b588bc36889e73c960f7d53f320a5d4429cb817f5459fe4cae0d0f08b3cL79-R109): Updated the version of all `Microsoft.Kiota` dependencies to `1.19.0`.
* [`src/Core/ApiClientCodeGen.Tests.Common/Build/Projects/KiotaProjectFileContents.cs`](diffhunk://#diff-4803d3275bddea639ee0b07c0b2d62a4dfc82aed8f67ead1bdb0b2df0d0e4d50L12-R17): Updated the `Microsoft.Kiota` package references for both `net8.0` and `netstandard2.1` target frameworks to version `1.19.0`. …
=> Update Microsoft Kiota dependencies to version 1.19.0
